# Generated by Django 4.1.1 on 2022-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=20)),
                ('teachersurname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('teacherphone', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('study_field', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=30)),
                ('course_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
