# Generated by Django 4.0 on 2022-01-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
