# Generated by Django 4.0 on 2022-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiry', '0002_delete_userquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=30)),
                ('course_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
