# Generated by Django 4.1 on 2022-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=20)),
                ('teachersurname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('teacherphone', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('study_field', models.CharField(max_length=30)),
            ],
        ),
    ]
