# Generated by Django 4.0 on 2022-04-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_slogan', models.CharField(max_length=50)),
                ('course_location', models.CharField(max_length=100)),
                ('course_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('course_profile', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_select', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=30)),
                ('exam_content', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('empty_space', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branchs')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=50)),
                ('photo', models.ImageField(max_length=30, upload_to='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branchs')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss')),
            ],
        ),
        migrations.AddField(
            model_name='courseboss',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetype'),
        ),
        migrations.AddField(
            model_name='courseboss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='CourseApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_student', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('student_surname', models.CharField(max_length=30)),
                ('apply_title', models.CharField(max_length=30)),
                ('apply_content', models.CharField(max_length=100)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('student_email', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Ad')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Rəy')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.courseboss', verbose_name='Kurs')),
            ],
        ),
        migrations.AddField(
            model_name='branchs',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss'),
        ),
    ]
