# Generated by Django 4.1.1 on 2022-10-15 22:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField(verbose_name='Location URL')),
                ('adress', models.CharField(max_length=255, verbose_name='Ünvan')),
                ('contact', models.CharField(max_length=30, verbose_name='Əlaqə nömrəsi')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Ad')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Rəy')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('cancel', models.BooleanField(default=False)),
                ('apply_title', models.CharField(max_length=30, verbose_name='Müraciət başlığı')),
                ('apply_content', models.CharField(max_length=100, verbose_name='Müraciət mövzusu')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_course', models.BooleanField(default=False)),
                ('course_name', models.CharField(max_length=30, verbose_name='Kurs adı')),
                ('course_phone', models.CharField(max_length=200, verbose_name='Nömrəsi')),
                ('course_slogan', models.CharField(max_length=50, verbose_name='Slogan')),
                ('course_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('course_location', models.URLField(verbose_name='Kursun məkanı')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Kursun saytı')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('course_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kurs logosu')),
                ('course_profile', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kurs profil şəkili')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(max_length=30, upload_to='', verbose_name='Şəkil')),
            ],
        ),
        migrations.CreateModel(
            name='CourseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('group_price', models.CharField(max_length=50)),
                ('prsonal_price', models.CharField(max_length=50)),
                ('about_service', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_select', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CreateBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='Məqalə başlığı')),
                ('blog_content', ckeditor.fields.RichTextField(verbose_name='Məqalə Mövzusu')),
                ('photo', models.ImageField(max_length=50, upload_to='', verbose_name='Şəkil')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Event başlığı')),
                ('content', ckeditor.fields.RichTextField()),
                ('start_date', models.DateField(verbose_name='Qeydiyyatın başlaması')),
                ('end_date', models.DateField(verbose_name='Qeydiyyatın bitməsi')),
                ('event_day', models.DateField(verbose_name='Təlimin başlaması')),
                ('event_location', models.URLField(verbose_name='Ünvan URL')),
                ('event_adress', models.CharField(max_length=200, verbose_name='Adres')),
                ('photo', models.ImageField(max_length=30, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EventApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.IntegerField()),
                ('apply_case', models.CharField(max_length=200, verbose_name='Müraciət səbəbi')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=30, verbose_name='Imtahanın adı')),
                ('exam_content', models.CharField(max_length=50, verbose_name='İmtahan haqqında')),
                ('exam_date', models.DateField(verbose_name='imtahan tarixi')),
                ('empty_space', models.CharField(max_length=10, verbose_name='Boş yerlər')),
            ],
        ),
        migrations.CreateModel(
            name='ExamApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_surname', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_select', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('study_field', models.CharField(max_length=100, verbose_name='Tədris sahəsi')),
                ('experience', models.CharField(max_length=50, verbose_name='Təcrübə')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='İnstagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('study_plan', ckeditor.fields.RichTextField()),
                ('note', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('cancel', models.BooleanField(default=False)),
                ('apply_title', models.CharField(max_length=30, verbose_name='Müraciət başlığı')),
                ('apply_content', models.CharField(max_length=255, verbose_name='Müraciət mövzusu')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.trainer')),
            ],
        ),
    ]
