# Generated by Django 4.1.1 on 2022-10-02 16:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField()),
                ('adress', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Ad')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Rəy')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('cancel', models.BooleanField(default=False)),
                ('apply_title', models.CharField(max_length=30)),
                ('apply_content', models.CharField(max_length=100)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_course', models.BooleanField(default=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_phone', models.CharField(max_length=200)),
                ('course_slogan', models.CharField(max_length=50)),
                ('course_email', models.EmailField(max_length=254)),
                ('course_location', models.URLField()),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField()),
                ('course_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('course_profile', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(max_length=30, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_select', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_day', models.DateField()),
                ('event_location', models.URLField()),
                ('event_adress', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=30, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EventApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.IntegerField()),
                ('apply_case', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=30)),
                ('exam_content', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('empty_space', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_surname', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonplan', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_select', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('study_field', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('study_plan', ckeditor.fields.RichTextField()),
                ('note', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('cancel', models.BooleanField(default=False)),
                ('apply_title', models.CharField(max_length=30)),
                ('apply_content', models.CharField(max_length=100)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.trainer')),
            ],
        ),
    ]
