# Generated by Django 4.1.1 on 2022-09-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
