# Generated by Django 4.0 on 2022-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapply',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
