# Generated by Django 4.1.1 on 2022-10-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_useranswer_answercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answercourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseanswer'),
        ),
    ]
