# Generated by Django 4.0 on 2022-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseapply_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapply',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseapply',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
