# Generated by Django 4.1.1 on 2022-10-15 23:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonplan', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courseboss',
            name='is_premium',
        ),
        migrations.DeleteModel(
            name='CourseService',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
