# Generated by Django 4.1.1 on 2022-10-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchs',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='branchs',
            name='contact',
            field=models.CharField(max_length=30, verbose_name='Əlaqə nömrəsi'),
        ),
        migrations.AlterField(
            model_name='branchs',
            name='location',
            field=models.URLField(verbose_name='Location URL'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_location',
            field=models.URLField(verbose_name='Kursun məkanı'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kurs logosu'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_name',
            field=models.CharField(max_length=30, verbose_name='Kurs adı'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_phone',
            field=models.CharField(max_length=200, verbose_name='Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_profile',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kurs profil şəkili'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_slogan',
            field=models.CharField(max_length=50, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetype', verbose_name='Kursun tipi'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='facebook',
            field=models.URLField(verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='courseboss',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Kursun saytı'),
        ),
        migrations.AlterField(
            model_name='coursephoto',
            name='photo',
            field=models.ImageField(max_length=30, upload_to='', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='coursephoto',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Qeydiyyatın bitməsi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_adress',
            field=models.CharField(max_length=200, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.DateField(verbose_name='Təlimin başlaması'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.URLField(verbose_name='Ünvan URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Qeydiyyatın başlaması'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Event başlığı'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branchs', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='empty_space',
            field=models.CharField(max_length=10, verbose_name='Boş yerlər'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_content',
            field=models.CharField(max_length=50, verbose_name='İmtahan haqqında'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(verbose_name='imtahan tarixi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_title',
            field=models.CharField(max_length=30, verbose_name='Imtahanın adı'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.CharField(max_length=50, verbose_name='Təcrübə'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='facebook',
            field=models.URLField(verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='İnstagram'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.location', verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='study_field',
            field=models.CharField(max_length=100, verbose_name='Tədris sahəsi'),
        ),
    ]
