# Generated by Django 4.1.1 on 2022-09-23 04:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_event_adress_remove_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursephoto',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
