# Generated by Django 4.1.1 on 2022-10-09 15:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_branchs_adress_alter_branchs_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='Məqalə başlığı')),
                ('blog_content', ckeditor.fields.RichTextField(verbose_name='Məqalə Mövzusu')),
                ('photo', models.ImageField(max_length=50, upload_to='', verbose_name='Şəkil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
