# Generated by Django 4.1.1 on 2022-10-15 23:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_lessonplan_remove_courseboss_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('group_price', models.CharField(max_length=50)),
                ('prsonal_price', models.CharField(max_length=50)),
                ('about_service', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='courseboss',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LessonPlan',
        ),
        migrations.AddField(
            model_name='courseservice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss'),
        ),
        migrations.AddField(
            model_name='courseservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
