# Generated by Django 4.0 on 2022-05-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courseapply_cancel_courseapply_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtypeselect', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExamApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_surname', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('last_year', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('cardtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.card')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseboss')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.exam')),
            ],
        ),
    ]
