# Generated by Django 4.0 on 2022-05-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_card_examapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examapply',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='examapply',
            name='cardtype',
        ),
        migrations.RemoveField(
            model_name='examapply',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='examapply',
            name='last_year',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
