# Generated by Django 4.1.1 on 2022-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courseservice_delete_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseboss',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
