# Generated by Django 4.1.1 on 2022-10-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseanswer_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answercourse',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='course',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseAnswer',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
