# Generated by Django 4.1.1 on 2022-10-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='User şəkili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Istifadəçi adı'),
        ),
    ]
