# Generated by Django 4.1.1 on 2022-11-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
    ]
