# Generated by Django 4.1 on 2022-08-31 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='teacher_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
