# Generated by Django 4.1 on 2022-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_is_course_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_course',
        ),
        migrations.AddField(
            model_name='user',
            name='is_course',
            field=models.BooleanField(default=False),
        ),
    ]
