# Generated by Django 4.1.1 on 2022-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_course_is_course_user_is_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
