# Generated by Django 4.1.1 on 2022-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_course',
        ),
    ]
