# Generated by Django 4.1.1 on 2022-09-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_is_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
