from django.urls import path

from course import views

app_name = "course"

urlpatterns = [
    path('courses', views.courses, name="courses"),
    path('aboutus', views.aboutus, name="aboutus"),
    path('addcourse', views.addcourse, name="addcourse"),
    path('addtrainer', views.addtrainer, name="addtrainer"),
    path(r'addbranch/(?P<id>[0-20]+)?$', views.addbranch, name="addbranch"),
    path(r'detailcourse/(?P<id>[0-9]+)?$', views.detailcourse, name="detailcourse"),
    path(r'detailtrainers/(?P<id>[0-9]+)?$', views.detailtrainers, name="detailtrainers"),
    path(r'updatecourse/(?P<id>[0-9]+)?$', views.updatecourse, name="updatecourse"),
    path(r'updatetrainer/(?P<id>[0-30]+)?$', views.updatetrainer, name="updatetrainer"),
    path(r'deletecourse/(?P<id>[0-25]+)?$', views.deletecourse, name="deletecourse"),
    path(r'updatebranch/(?P<id>[0-26]+)?$', views.updatebranch, name="updatebranch"),
    path(r'deletebranch/(?P<id>[0-24]+)?$', views.deletebranch, name="deletebranch"),
    path('comment/<int:id>', views.comment, name="comment"),
    path(r'addphoto/(?P<id>[0-15]+)?$', views.addphoto, name="addphoto"),
    path(r'blogdetails/(?P<id>[0-12]+)?$', views.blogdetails, name="blogdetails"),
    path(r'gallery/(?P<id>[0-27]+)?$', views.gallery, name="gallery"),
    path(r'addexam/(?P<id>[0-8]+)?$', views.addexam, name="addexam"),
    path(r'courseexam/(?P<id>[0-19]+)?$', views.courseexam, name="courseexam"),
    path(r'courseapply/(?P<id>[0-63]+)?$', views.courseapply, name="courseapply"),
    path(r'applytrainer/(?P<id>[0-18]+)?$', views.applytrainer, name="applytrainer"),
    path(r'addservice/(?P<id>[0-32]+)?$', views.addservice, name = "addservice"),
    path(r'updateservice/(?P<id>[0-33]+)?$', views.updateservice, name = "updateservice"),
    path(r'deleteservice/(?P<id>[0-41]+)?$', views.deleteservice, name = "deleteservice"),
    path(r'detailservice/(?P<id>[0-54]+)?$', views.detailservice, name = "detailservice"),
    path(r'coursenotification/(?P<id>[0-65]+)?$',
         views.coursenotification, name="coursenotification"),
    path(r'courseapplynotification/(?P<id>[0-74]+)?$',
         views.courseapplynotification, name="courseapplynotification"),
    path('commonnotification/', views.commonnotification,
         name="commonnotification"),
    path(r'trainernotification/(?P<id>[0-16]+)?$',
         views.trainernotification, name="trainernotification"),
    path(r'trainerapplynotification/(?P<id>[0-44]+)?$',
         views.trainerapplynotification, name="trainerapplynotification"),
    path(r'confirm/(?P<id>[0-78]+)?$', views.confirm, name="confirm"),
    path(r'confirmtrainer/(?P<id>[0-79]+)?$', views.confirmtrainer, name="confirmtrainer"),
    path(r'canceltrainer/(?P<id>[0-93]+)?$', views.canceltrainer, name="canceltrainer"),
    path(r'cancel/(?P<id>[0-39]+)?$', views.cancel, name="cancel"),
    path('tests', views.tests, name="tests"),
    path(r'applyexam/(?P<id>[0-13]+)?$', views.applyexam, name="applyexam"),
    path(r'addevent/(?P<id>[0-46]+)?$', views.addevent, name="addevent"),
    path(r'eventdetails/(?P<id>[0-44]+)?$', views.eventdetails, name="eventdetails"),
    path(r'deleteevent/(?P<id>[0-77]+)?$', views.deleteevent, name="deleteevent"),
    path(r'deletetrainer/(?P<id>[0-81]+)?$', views.deletetrainer, name="deletetrainer"),
    path(r'updateevent/(?P<id>[0-56]+)?$', views.updateevent, name="updateevent"),
    path(r'applyevent/(?P<id>[0-62]+)?$', views.applyevent, name="applyevent"),
    path('faq', views.faq, name="faq"),
    path('createblog', views.createblog, name="createblog"),
    path('articles', views.articles, name="articles"),
    path(r'commonarticledetails/(?P<id>[0-71]+)?$', views.commonarticledetails, name="commonarticledetails"),
    path(r'updatearticle/(?P<id>[0-86]+)?$', views.updatearticle, name="updatearticle"),
    path(r'deletearticle/(?P<id>[0-88]+)?$', views.deletearticle, name="deletearticle"),
    path(r'eventapplynotification/(?P<id>[0-76]+)?$',
         views.eventapplynotification, name="eventapplynotification"),
    path(r'coursemessage/(?P<id>[0-68]+)?$',views.coursemessage, name="coursemessage"),
    path(r'usermessage/(?P<id>[0-98]+)?$',views.usermessage, name="usermessage"),
]
